import { chromium } from "playwright-core";
import { existsSync } from "node:fs";
const CHROME = [`${process.env.HOME}/.cache/ms-playwright/chromium-1217/chrome-linux64/chrome`,
  `${process.env.HOME}/.cache/ms-playwright/chromium-1200/chrome-linux64/chrome`].find(p => existsSync(p));
const browser = await chromium.launch({ executablePath: CHROME });
const page = await browser.newPage({ viewport: { width: 1440, height: 860 }, deviceScaleFactor: 1 });
await page.goto("https://franken-markdown.com/", { waitUntil: "networkidle" });
await page.waitForFunction(() => document.getElementById("pg-status")?.textContent?.includes("ALIVE"), null, { timeout: 45000 });
await page.waitForTimeout(3400);
await page.screenshot({ path: "screenshots/hero.png" });
await page.locator("#playground").scrollIntoViewIfNeeded();
await page.evaluate(() => window.scrollBy(0, -70));
await page.locator("#pg-toggle-pdf").click();
await page.waitForFunction(() => document.getElementById("pg-pdf-frame")?.src.startsWith("blob:"), null, { timeout: 30000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: "screenshots/playground-pdf.png" });
await page.locator("#pg-maximize").click();
await page.waitForTimeout(600);
await page.screenshot({ path: "screenshots/maximized.png" });
await page.keyboard.press("Escape");
await page.locator("#viz-knuth").scrollIntoViewIfNeeded();
await page.evaluate(() => window.scrollBy(0, -60));
await page.waitForTimeout(1200);
await page.screenshot({ path: "screenshots/knuth-plass.png" });
await browser.close();
console.log("repo screenshots done");
